- README.md
Simply corrected a misspelling of "Address" in the link to Address Sanitizer.
> Correct typo for address sanitizer

- Package.swift
> Remove the benchmark product from the package manifest

- Package.resolved
- swift-collections.xcworkspace/xcshareddata/swiftpm/Package.resolved
(This only affects local development. Oh, and CI.)
> [meta] Update dependencies

- Sources/DequeModule/_DequeBuffer.swift
Replace this paragraph with a description of your changes and rationale. Provide links to an existing issue or external references/discussions, if appropriate.
> [Deque][NFC] Remove unused code

- Documentation/Heap.md
- Sources/PriorityQueueModule/Heap.swift
- Use a persistent DOI-based link rather than linking to ephemeral course material.
- Replace the example heap (borrowed from Wikipedia) with a better one.
> [Heap] Update implementation details section in docs

- swift-collections.xcworkspace/contents.xcworkspacedata
This makes it easier to edit benchmarks in Xcode.
> Add Benchmarks package to workspace

- Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Deprecations.swift
- Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Elements+SubSequence.swift
- Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Elements.swift
- Sources/OrderedCollections/OrderedSet/OrderedSet+RandomAccessCollection.swift
- Sources/OrderedCollections/OrderedSet/OrderedSet+SubSequence.swift
(Hm, shepherding these will grow old pretty soon. Perhaps it'd better to just land changes on the release branch and regularly merge them to `main` from there.)
> Cherry pick recent changes on main to release/1.0

- README.md
> [README] Note that `Heap` hasn't been tagged yet & list other enhancements in progress

- Utils/run-full-tests.sh
> [run-full-tests.sh] Fix bashism: == vs =

- Documentation/OrderedSet.md
- Sources/OrderedCollections/OrderedSet/OrderedSet.swift
> [OrderedSet][doc] Fix thinko

- Utils/swift-collections.xcworkspace/xcshareddata/IDETemplateMacros.plist
- Utils/swift-collections.xcworkspace/xcshareddata/xcschemes/Collections.xcscheme
Update Collections scheme with support for testing.
Update the copyright year in file template.
> [Xcode] Update schemes & file template

- Sources/OrderedCollections/OrderedSet/OrderedSet+UnorderedView.swift
> [OrderedSet] Work around weird name lookup issue in compiler

- README.md
This just bumps the sample code for adding this package as a dependency to require current versions.
> Update README for 1.0.3

- README.md
- Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Initializers.swift
- Sources/OrderedCollections/OrderedDictionary/OrderedDictionary.swift
- Tests/OrderedCollectionsTests/OrderedDictionary/OrderedDictionary Tests.swift
- Utils/swift-collections.xcworkspace/xcshareddata/xcschemes/OrderedCollections.xcscheme
- Utils/swift-collections.xcworkspace/xcshareddata/xcschemes/swift-collections-Package.xcscheme
This picks up any changes from the 1.0.3 release that weren't already on the main branch.
> Merge release/1.0 branch to main

- Sources/BitCollections/Shared/_Word.swift
As discovered by @benrimmington over in #143-- thanks!
> [BitSet] Fix decoding format on 32 bit architectures

- Documentation/OrderedDictionary.md
- Sources/OrderedCollections/OrderedSet/OrderedSet+Partial SetAlgebra+Predicates.swift
> Merge release/1.0 to release/1.1

- Package.swift
- Sources/HeapModule/Heap+Invariants.swift
- Sources/HeapModule/Heap+UnsafeHandle.swift
- Sources/HeapModule/Heap.swift
- Sources/HeapModule/_Node.swift
- Sources/_CollectionsTestSupport/AssertionContexts/Combinatorics.swift
- Tests/CollectionsTestSupportTests/CombinatoricsChecks.swift
- Tests/HeapTests/HeapTests.swift
- Tests/PersistentCollectionsTests/Utilities.swift
- Update tests to use _CollectionsTestSupport infrastructure; add some new combinatorial tests
- Review & slightly update API docs (more is coming)
- Fix a typo that prevented internal checks from working correctly
> [Heap] Prerelease preparations

- Package.swift
> [manifest] Exclude CMakeLists.txt; remove unnecessary path settings; reindent file

- Sources/OrderedCollections/OrderedSet/OrderedSet+Initializers.swift
- Sources/OrderedCollections/OrderedSet/OrderedSet+Partial SetAlgebra+Basics.swift
> [OrderedSet] Small doc updates/fixes

- Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Partial MutableCollection.swift
- Sources/OrderedCollections/OrderedDictionary/OrderedDictionary.Elements.swift
- Sources/OrderedCollections/OrderedSet/OrderedSet+Initializers.swift
- Sources/OrderedCollections/OrderedSet/OrderedSet+Partial MutableCollection.swift
- Sources/OrderedCollections/OrderedSet/OrderedSet+Partial SetAlgebra+Basics.swift
Merge changes from release/1.0 into release/1.1.
> Merge.1.0→1.1

- Sources/OrderedCollections/OrderedSet/OrderedSet+Initializers.swift
- Test for `_UniqueCollection` conformance instead of individual types
- Better memory management
> [OrderedSet] Improve sequence-taking initializer

- Sources/PersistentCollections/PersistentSet/PersistentSet+Sequence.swift
For a cool 4x performance improvement. 😣
> [PersistentSet] Iterator.next(): Make inlinable

- Tests/SortedCollectionsTests/BTree/BTree Tests.swift
- Tests/SortedCollectionsTests/BTree/BTree+Deletion Tests.swift
- Tests/SortedCollectionsTests/BTree/BTree.Builder Tests.swift
- Tests/SortedCollectionsTests/BTree/Node Utils.swift
- Tests/SortedCollectionsTests/BTree/Node+Balancing Tests.swift
- Tests/SortedCollectionsTests/BTree/Node+Insertion Tests.swift
- Tests/SortedCollectionsTests/BTree/Node+Join Tests.swift
- Tests/SortedCollectionsTests/BTree/NodeTests.swift
- Tests/SortedCollectionsTests/SortedDictionary/SortedDictionary Tests.swift
> [SortedCollections] Disable tests with @testable imports in release builds

- Benchmarks/Libraries/PersistentSet.json
- Benchmarks/Sources/Benchmarks/PersistentSetBenchmarks.swift
- Benchmarks/Sources/Benchmarks/SetBenchmarks.swift
- Sources/Collections/Collections.docc/Extensions/PersistentDictionary.md
- Sources/Collections/Collections.docc/Extensions/PersistentSet.md
- Sources/PersistentCollections/PersistentCollections.docc/Extensions/PersistentDictionary.md
- Sources/PersistentCollections/PersistentCollections.docc/Extensions/PersistentSet.md
- Sources/PersistentCollections/PersistentDictionary/PersistentDictionary.swift
> [PersistentCollections] Doc & benchmark updates in preparation of API review

- Sources/BitCollections/CMakeLists.txt
- Sources/_CollectionsUtilities/CMakeLists.txt
> [cmake] Update CMake configuration

- Sources/OrderedCollections/OrderedDictionary/OrderedDictionary.swift
This is a cherry pick of #254 to the `release/1.1` branch.
> [OrderedDictionary] Explicitly mention in documentation that keys/values are ordered

- Sources/RopeModule/Rope/Basics/Rope+_Node.swift
- Sources/RopeModule/Rope/Basics/Rope+_Storage.swift
- Sources/RopeModule/Rope/Basics/Rope+_UnmanagedLeaf.swift
- Sources/RopeModule/Rope/Basics/Rope+_UnsafeHandle.swift
- Sources/RopeModule/Rope/Basics/Rope.swift
- Sources/RopeModule/Rope/Basics/_RopeItem.swift
This doesn't actually make anything ABI stable, but it does let this module be built with library evolution enabled.
> [RopeModule] Fix issues in Swift's ABI stable dialect

- Documentation/Internals/ReleaseChecklist.md
Add two steps, about pre-announcing nontrivial releases and about updating the dependency configuration in the Swift toolchain.
> Update release checklist

- Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Elements+SubSequence.swift
- Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Elements.swift
- Sources/OrderedCollections/OrderedDictionary/OrderedDictionary.swift
> [OrderedDictionary] Fix usage of deprecated API in index(forKey:) docs

- README.md
> Merge.1.1→main

- Sources/Future/RawSpan.swift
- Sources/Future/Span.swift
- Tests/FutureTests/ContiguousStorageTests.swift
- Tests/FutureTests/RawSpanTests.swift
- Tests/FutureTests/SpanTests.swift
Parsing utilities for `RawSpan`, thanks to @milseman.
Examples of their use are pending.
> Extras for `RawSpan`

- Sources/Future/RawSpan.swift
- Sources/Future/Span.swift
- Tests/FutureTests/RawSpanTests.swift
- Tests/FutureTests/SpanTests.swift
Improve internal representation of `Span`, simultaneously making it tolerant of nil-based `UnsafeBufferPointer` inputs.
This was slightly more invasive than expected, but it's not bad. It required minor changes in the implementations of the "containment" functions, the one-sided and the unchecked `extracting()` overloads, and the single-element subscript.
> Improve internal representation of `Span`

- Sources/DequeModule/RigidDeque.swift
- Sources/Future/Arrays/DynamicArray.swift
- Sources/Future/Arrays/NewArray.swift
- Sources/Future/Arrays/RigidArray.swift
- Sources/Future/Containers/Container.swift
- Sources/Future/Containers/ContainerAlgorithms.swift
- Sources/Future/Containers/MutableContainer.swift
- Sources/Future/Containers/RepeatingContainer.swift
- Tests/BitCollectionsTests/BitArrayTests.swift
- Tests/CollectionsTestSupportTests/MinimalTypeConformances.swift
- Tests/DequeTests/DequeTests.swift
- Tests/FutureTests/DynamicArrayTests.swift
- Tests/FutureTests/RigidArrayTests.swift
- Tests/HashTreeCollectionsTests/TreeDictionary Tests.swift
- Tests/HashTreeCollectionsTests/TreeSet Tests.swift
- Tests/OrderedCollectionsTests/OrderedDictionary/OrderedDictionary Tests.swift
- Tests/OrderedCollectionsTests/OrderedSet/OrderedSetTests.swift
- Tests/SortedCollectionsTests/SortedSet/SortedSet Tests.swift
- Tests/_CollectionsTestSupport/AssertionContexts/Assertions+Containers.swift
- Tests/_CollectionsTestSupport/AssertionContexts/Assertions.swift
- Tests/_CollectionsTestSupport/MinimalTypes/TestContainer.swift
- Tests/_CollectionsTestSupport/Utilities/LifetimeTracker.swift
Add a first cut of most basic removal/insertion/range-replacement operations to `RigidArray`, with some test coverage.
Add a few simple Container algorithms to help with testing.
> Flesh out RigidArray; try adding some Container algorithms

- Package.swift
- Sources/BitCollections/BitArray/BitArray+BitwiseOperations.swift
- Sources/BitCollections/BitArray/BitArray+Codable.swift
- Sources/BitCollections/BitArray/BitArray+Initializers.swift
- Sources/BitCollections/BitArray/BitArray+RandomBits.swift
- Sources/BitCollections/BitArray/BitArray+Testing.swift
- Sources/BitCollections/BitSet/BitSet+BidirectionalCollection.swift
- Sources/BitCollections/BitSet/BitSet+Random.swift
- Sources/BitCollections/BitSet/BitSet+SetAlgebra basics.swift
> Enable MemberImportVisibility and fix issues uncovered

- Benchmarks/Libraries/BigString.json
- Benchmarks/Sources/Benchmarks/BigStringBenchmarks.swift
- Sources/RopeModule/BigString/Basics/BigString+Contents.swift
- Sources/RopeModule/BigString/Basics/BigString+Metrics.swift
- Sources/RopeModule/BigString/Chunk/BigString+Chunk+Indexing by Characters.swift
- Tests/RopeModuleTests/TestBigString.swift
This is a regular maintenance merge to pick up recently landed changes.
> Merge changes on `release/1.2` to `main` branch

- Xcode/Collections.xcodeproj/project.pbxproj
We forgot to add these to the xcodeproj, so add this rename here.
> Add BasicContainer rename to xcodeproj

- README.md
- Sources/BasicContainers/BasicContainers.docc/BasicContainers.md
- Sources/BasicContainers/BasicContainers.docc/Extensions/RigidArray.md
- Sources/BasicContainers/BasicContainers.docc/Extensions/UniqueArray.md
- Sources/Collections/Collections.docc/Collections.md
> One last round of documentation updates
