.github/PULL_REQUEST_TEMPLATE/NEW.md, Sources/OrderedCollections/OrderedDictionary/OrderedDictionary.swift
Fixed two minor documentation issues 
1. The first reported in the [swift forums]( https://forums.swift.org/t/minor-issue-in-documentation-of-ordereddictionary-updatevalue/47195) in documentation for function OrderedDictionary.updateValue. changing `updateOrInsertValue(_:forKey:at:)` to `updateValue(_:forKey:insertingAt:)` 
2. The second reported in https://github.com/apple/swift-collections/pull/6#issuecomment-813865398 , the default new pull request templet has an incorrect link to the Contribution Guidelines
- [ x] I've read the [Contribution Guidelines](../../CONTRIBUTING.md)
- [ x] My contributions are licensed under the [Swift license](https://swift.org/LICENSE.txt).
- [ x] I've followed the coding style of the rest of the project.
- [ x] I've verified that my change does not break …
=> Minor doc fix

Sources/OrderedCollections/OrderedSet/OrderedSet+ReserveCapacity.swift
This sentence refers to a `reserveCapacity` variant that did not end up in the public OrderedSet API. (It remains internal for now.)
=> Remove outdated passage in `OrderedSet.init(minimumCapacity:persistent:)` docs

Package.resolved
Replace this paragraph with a description of your changes and rationale. Provide links to an existing issue or external references/discussions, if appropriate.
=> Update Package.resolved with swift-collections-benchmark package

README.md
The link to [Combinatorics](https://github.com/apple/swift-collections/blob/main/Sources/CollectionsTestSupport/Combinatorics) appears to be wrong, this change updates it to [Combinatorics.swift](https://github.com/apple/swift-collections/blob/main/Sources/CollectionsTestSupport/AssertionContexts/Combinatorics.swift).
=> Fixes link to combinatorics.

Benchmarks/Benchmarks/OrderedSetBenchmarks.swift, Sources/OrderedCollections/OrderedSet/OrderedSet+Diffing.swift, Tests/OrderedCollectionsTests/OrderedSet/OrderedSet Diffing Tests.swift
Adds an overload of `difference(from:)` that implements a linear time algorithm (same as used by Foundation's `NSOrderedSet`, SwiftUI's `List`, and UIKit's Diffable Data Source), as well as an implementation of `applying(:)` that is linear, though slower than if `OrderedSet` conformed to `RangeReplaceableCollection`.
```swift
extension OrderedSet {
/// Returns the collection difference between the parameter and the
/// receiver, using an algorithm specialized to exploit fast membership
/// testing and the member uniqueness guarantees of `OrderedSet`.
///
/// - Complexity: O(`self.count + other.count`)
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
public func difference(
from other: Self
) -> CollectionDifference<Element>
/// Applies the given difference to this collection.
/// …
```
=> Efficient diffing for OrderedSet

.swiftpm/xcode/xcshareddata/xcschemes/swift-collections-Package.xcscheme, .swiftpm/xcode/xcshareddata/xcschemes/swift-collections-benchmark.xcscheme
These are used when we open the package folder in Xcode; they contain configuration settings (such as enabling code coverage collection) that is missing from Package.swift.
This update makes these stop referring to nonexistent targets and commit some changes that Xcode adds on its own every time we open the project.
=> Update Xcode schemes for the package

Sources/OrderedCollections/OrderedSet/OrderedSet+Insertions.swift
Fixes #19.
It does not seem appropriate to write a test for this change. However, I am open to other points of view and will gladly own further work.
=> Add the @discardableResult attribute to OrderedSet.insert(_:at:)

Sources/CollectionsTestSupport/AssertionContexts/CollectionTestCase.swift
Fixes https://github.com/apple/swift-collections/issues/17
Removes calling XCTestCase's setup on the CollectionTestCase tearDown method. Implementation is similar to the solution provided on the issue.
=> Fix CollectionTestCase calling super's setup on tearDown issue

Package.resolved
This PR bumps the pinned version number of the swift-collections-benchmark dependency to 0.0.2. 
(Pinning only takes effect on direct builds of this package, not when the package is merely used as a dependency.)
=> Update to swift-collections-benchmark 0.0.2

Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Codable.swift
Unlike the regular unordered `Dictionary`, `OrderedDictionary` always encodes/decodes itself as alternating key/value pairs in an unkeyed container. Document this fact (and the reason behind it) in the `Decodable` implementation.
Resolves #12.
=> [OrderedDictionary] Document encoding format

Sources/DequeModule/Deque+MutableCollection.swift, Sources/DequeModule/Deque+RandomAccessCollection.swift, Sources/DequeModule/Deque+RangeReplaceableCollection.swift, Sources/DequeModule/Deque+Sequence.swift, Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Elements.swift, Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Partial MutableCollection.swift, Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Values.swift, Sources/OrderedCollections/OrderedDictionary/OrderedDictionary.swift, Sources/OrderedCollections/OrderedSet/OrderedSet+Insertions.swift, Sources/OrderedCollections/OrderedSet/OrderedSet+Partial MutableCollection.swift, Sources/OrderedCollections/OrderedSet/OrderedSet+Partial RangeReplaceableCollection.swift, Sources/OrderedCollections/OrderedSet/OrderedSet+RandomAccessCollection.swift, Sources/OrderedCollections/OrderedSet/OrderedSet+SubSequence.swift, Sources/OrderedCollections/OrderedSet/OrderedSet.swift
Closes #30. I tried to find all instances of Int where Index should have been used in the Source. I did not search the tests because the issue is semantic only, and my changes only have impact on the public API.
=> Replace Index with Int where possible

swift-collections.xcworkspace/xcshareddata/IDETemplateMacros.plist
This adds an `IDETemplateMacros.plist` which means all files created through Xcode automatically have the correct header comment generated with them.
=> Add Xcode template file with license comment.

CMakeLists.txt, Sources/CMakeLists.txt, Sources/Collections/CMakeLists.txt, Sources/DequeModule/CMakeLists.txt, Sources/OrderedCollections/CMakeLists.txt, cmake/modules/SwiftSupport.cmake
Add a CMake based build system to enable bootstrapping the toolchain
with the ability to use Swift Collections in SPM.
Replace this paragraph with a description of your changes and rationale. Provide links to an existing issue or external references/discussions, if appropriate.
=> build: add a CMake based build system

Sources/DequeModule/Compatibility.swift, Sources/DequeModule/Deque+Extras.swift, Sources/DequeModule/Deque+RangeReplaceableCollection.swift, Tests/DequeTests/DequeTests.swift, Tests/DequeTests/RangeReplaceableCollectionTests.swift
Resolves #27 by updating `Deque.init(_:)`, `.append(contentsOf:)` and `.prepend(contentsOf:)` to not call `Array.withContiguousStorageIfAvailable` if there is a chance doing so may trigger the underlying stdlib issue.
=> [Deque] Work around stdlib issue with Array.withContiguousStorageIfAvailable

Package.swift
The package manager doesn’t like it when it finds unexpected non-source files in source directories.
=> [manifest] Ignore CMake files

Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Invariants.swift
Currently, `OrderedDictionary._checkInvariants()` delegates to `_UnstableInternals._checkInvariants()` which doesn't exist. This updates the invariant check to delegate to the invariant check on `OrderedSet` instead.
=> Update invalid OrderedDictionary invariant check.

Sources/OrderedCollections/OrderedSet/OrderedSet+Insertions.swift
When calling `insert(_:at:)` the returned index may be different than the requested index in case `selected` is **false** rather than true
=> Fixing a small typo on quick help docs

Tests/OrderedCollectionsTests/OrderedSet/OrderedSet Diffing Tests.swift
The `OrderedSetDiffingTests` are testing `difference` and `applying` methods on the `OrderedSet` type. Those methods are defined in [`OrderedSet+Diffing.swift`](https://github.com/apple/swift-collections/blob/main/Sources/OrderedCollections/OrderedSet/OrderedSet%2BDiffing.swift) and have an availability annotation. That annotation was missing from the associated test class.
~~- [ ] I've added tests covering all new code paths my change adds to the project (if appropriate).~~
~~- [ ] I've added benchmarks covering new functionality (if appropriate).~~
~~- [ ] I've updated the documentation if necessary.~~
=> Mark OrderedSetDiffingTests with availability

CMakeLists.txt, cmake/modules/CMakeLists.txt, cmake/modules/SwiftCollectionsConfig.cmake.in
This is an integration FIXME for SwiftPM: https://github.com/apple/swift-package-manager/pull/3595#issuecomment-875201764
=> [CMake] swift-collections → SwiftCollections

.swiftpm/xcode/xcshareddata/xcschemes/swift-collections-Package.xcscheme, Package.swift, Sources/CollectionsTestSupport/ConformanceCheckers/CheckCollection.swift, Sources/CollectionsTestSupport/MinimalTypes/MinimalSequence.swift, Tests/CollectionsTestSupportTests/MinimalTypeConformances.swift
Also, try running the conformance checkers on the minimal collection types to catch similar issues.
Resolves #59.
=> [test] checkCollection: Don’t pass decreasing indices to distance(from:to:)

README.md
The markdown link has a closing bracket instead of a parenthesis.
=> Fix Markdown link in README

.swiftpm/xcode/xcshareddata/xcschemes/PriorityQueueModule.xcscheme, Sources/PriorityQueueModule/Heap+Invariants.swift, Sources/PriorityQueueModule/Heap+UnsafeHandle.swift, Sources/PriorityQueueModule/Heap.swift, Sources/PriorityQueueModule/_Node.swift, Tests/PriorityQueueTests/HeapTests.swift
- `@inline(__always)` has a detrimental effect when used on large functions. Let's not do that.
- Speed up invariant checking with COLLECTIONS_INTERNAL_CHECKS (resolves #69)
- Replace naked ints with `_Node`, precalculating levels for each offset (resolves #71)
- Rebase heap operations on UMBP instead Array, eliminating unnecessary index validation (resolves #75)
- ~Add some (slightly questionable) effects attributes to heap internals.~
- Optimize removals and heap construction
=> [Heap] Performance tweaks

Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Elements+SubSequence.swift, Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Elements.swift, Sources/OrderedCollections/OrderedDictionary/OrderedDictionary.swift
Typos in symbol documentation:
Subscripts are missing the `offset:` parameter.
=> Fix typos: missing subscript parameters

Documentation/OrderedDictionary.md, Sources/OrderedCollections/CMakeLists.txt, Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Deprecations.swift, Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Initializers.swift, Sources/OrderedCollections/OrderedDictionary/OrderedDictionary.swift, Tests/OrderedCollectionsTests/OrderedDictionary/OrderedDictionary Tests.swift
Resolves #90. This also adds a `with` label to the closure argument of these two methods, clarifying its role.
=> [OrderedDictionary] modifyValue → updateValue

Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Deprecations.swift, Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Elements.swift
Removed comments about using read only subscripts for in place mutations.
=> Documentation: Remove in-place mutation comments

Sources/DequeModule/Deque+Collection.swift, Sources/DequeModule/Deque._Storage.swift, Sources/DequeModule/Deque._UnsafeHandle.swift, Sources/DequeModule/_DequeBuffer.swift, Sources/DequeModule/_UnsafeWrappedBuffer.swift, Sources/OrderedCollections/OrderedSet/OrderedSet+UnorderedView.swift
Note: `@frozen` does *not* mean that we actually consider these struct types frozen. Their layout may arbitrarily change between even minor releases.
=> [1.0] Freeze some types for consistency with their inlinable initializers

Sources/DequeModule/Deque+Collection.swift, Sources/DequeModule/Deque._Storage.swift, Sources/DequeModule/Deque._UnsafeHandle.swift, Sources/DequeModule/_DequeBuffer.swift, Sources/DequeModule/_UnsafeWrappedBuffer.swift, Sources/OrderedCollections/OrderedSet/OrderedSet+UnorderedView.swift, Sources/PriorityQueueModule/Heap+OrderedViews.swift, Sources/PriorityQueueModule/Heap.swift
(This is the `main` branch counterpart for #97.)
Note: `@frozen` does *not* mean that we actually consider these struct types frozen. Their layout may arbitrarily change between even minor releases.
=> [main] Freeze some types for consistency with their inlinable initializers

Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Elements+SubSequence.swift, Sources/OrderedCollections/OrderedSet/OrderedSet+RandomAccessCollection.swift, Sources/OrderedCollections/OrderedSet/OrderedSet+SubSequence.swift
Renames a couple of non-public symbols which don't follow stdlib's [Leading Underscore Rule](https://github.com/apple/swift/blob/main/docs/StandardLibraryProgrammersManual.md#the-leading-underscore-rule):
```swift
OrderedDictionary.Elements.SubSequence.Iterator.init(_ base: OrderedDictionary.Elements.SubSequence)
```
changed to
```swift
OrderedDictionary.Elements.SubSequence.Iterator.init(_base: OrderedDictionary.Elements.SubSequence)
```
and
```swift
OrderedSet.SubSequence.init(base: OrderedSet, bounds: Range<Int>)
```
changed to 
```swift
OrderedSet.SubSequence.init(_base: OrderedSet, bounds: Range<Int>)
```
=> Follow stdlib's leading underscore rule

Tests/PriorityQueueTests/HeapTests.swift
These tests rely on @testable imports, which sadly won't work in optimized builds.
=> [Heap] Disable heap tests in release builds

Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Codable.swift, Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Initializers.swift, Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Partial MutableCollection.swift, Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Partial RangeReplaceableCollection.swift, Sources/OrderedCollections/OrderedDictionary/OrderedDictionary.swift, Sources/OrderedCollections/OrderedSet/OrderedSet+Insertions.swift, Sources/OrderedCollections/OrderedSet/OrderedSet+Invariants.swift, Sources/OrderedCollections/OrderedSet/OrderedSet+Partial RangeReplaceableCollection.swift, Sources/OrderedCollections/OrderedSet/OrderedSet+Partial SetAlgebra+Operations.swift, Sources/OrderedCollections/OrderedSet/OrderedSet+Testing.swift, Sources/OrderedCollections/OrderedSet/OrderedSet.swift
It seems useful to be able to manually call `_checkInvariants` while debugging a package issue. This is public as in `public`, not public as in Public API -- it's underscored.
This also adds more `_checkInvariants` invocations in functions that return newly created ordered sets.
=> [1.0][OrderedSet] Make _checkInvariants public and call it in more operations

Sources/OrderedCollections/OrderedSet/OrderedSet+Initializers.swift, Sources/OrderedCollections/OrderedSet/OrderedSet.swift
In debug builds, the `OrderedSet.init(uncheckedUniqueElements:)` initializer always created a set with no hash table, even if it had an element count >15. This is technically an invariant violation (caught by `_checkInvariants()`), although it generally only triggers (very) slow performance. (The set reverts to linear searching.)
=> [OrderedSet] Don't let the unchecked init create large sets with no hash table

cmake/modules/SwiftSupport.cmake
Seems like it is also possible for "aarch64" to be spelled lowercase, this fixes building on Ubuntu on arm at least.
=> [CMake] Match lowercase "aarch64"

Sources/OrderedCollections/OrderedSet/OrderedSet+Insertions.swift, Sources/_CollectionsTestSupport/AssertionContexts/Combinatorics.swift, Tests/OrderedCollectionsTests/OrderedDictionary/OrderedDictionary Tests.swift, Tests/OrderedCollectionsTests/OrderedDictionary/OrderedDictionary+Elements Tests.swift, Tests/OrderedCollectionsTests/OrderedDictionary/OrderedDictionary+Values Tests.swift, Tests/OrderedCollectionsTests/OrderedSet/OrderedSetTests.swift
`OrderedSet.insert(_:at:)` and `.updateOrInsert(_:at:)` accidentally violate value semantics by failing to check for uniqueness before updating the hash table. (`OrderedDictionary` is also affected, as it builds upon `OrderedSet`.)
Add the missing `_ensureUnique()` call and improve unit test coverage in this area.
Resolves #104.
Huge thanks to @KaiOelfke for providing a sample project that led to isolating the issue! 💙
=> [OrderedSet] Add missing uniqueness check

Utils/run-full-tests.sh
Update run-full-tests.sh to incorporate the improvements in swift-atomics.
- Keep going after a test execution failure.
- Split xcodebuild runs into separate instances per platform.
=> [Utils] run-full-tests.sh: Keep going after a failure

Utils/run-full-tests.sh
The version check is a bit of a hack, but this enables test discovery on 5.3 so the script can be used to test the package on that release without manual tweaking.
=> [Utils] run-full-tests.sh: Add support for testing on Swift 5.3 without manual editing

Sources/DequeModule/Deque+Collection.swift
Depending on the supplied sequence, `Deque.append(contentsOf:)` currently reserves just enough capacity as it needs to perform the append. This isn't right -- it can result in O(n) reallocs instead of O(log(n)) when items are incrementally appended in constant-sized `append(contents:)` batches.
=> [Deque] `append(contentsOf:):` Use exponential capacity reservation

Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Initializers.swift, Tests/OrderedCollectionsTests/OrderedDictionary/OrderedDictionary Tests.swift
This adds a new overload to help the type checker infer `[S.Element]` as the default `Value` type.
Resolves #139.
=> [OrderedDictionary] Fix type inference issue with `OrderedDictionary.init(grouping:by:)`

Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Initializers.swift, Tests/OrderedCollectionsTests/OrderedDictionary/OrderedDictionary Tests.swift
=> Merge `release/1.0` to `main`

Sources/OrderedCollections/OrderedDictionary/OrderedDictionary.swift
Resolves #145.
`OrderedDictionary` provides merge and filter operations that mostly come from the standard `Dictionary` type, and currently inherit documentation from them. Update docs to clarify the ordering of items in the result.
=> [OrderedDictionary][doc] Update docs for merge/filter operations

Utils/swift-collections.xcworkspace/xcshareddata/swiftpm/Package.resolved, Utils/swift-collections.xcworkspace/xcshareddata/xcschemes/Collections.xcscheme, Utils/swift-collections.xcworkspace/xcshareddata/xcschemes/CollectionsBenchmark.xcscheme, Utils/swift-collections.xcworkspace/xcshareddata/xcschemes/CollectionsTestSupport.xcscheme, Utils/swift-collections.xcworkspace/xcshareddata/xcschemes/DequeModule.xcscheme, Utils/swift-collections.xcworkspace/xcshareddata/xcschemes/OrderedCollections.xcscheme, Utils/swift-collections.xcworkspace/xcshareddata/xcschemes/PriorityQueueModule.xcscheme, Utils/swift-collections.xcworkspace/xcshareddata/xcschemes/benchmark.xcscheme, Utils/swift-collections.xcworkspace/xcshareddata/xcschemes/swift-collections-Package.xcscheme, Utils/swift-collections.xcworkspace/xcshareddata/xcschemes/swift-collections-benchmark-Package.xcscheme
This fixes and re-adds the custom Xcode build schemes that were removed in #155, this time hiding them under the development workspace `Utils/swift-collections.xcworkspace` so that they won't leak into dependent projects.
=> Reinstate custom schemes under Utils/swift-collections.xcworkspace

Sources/OrderedCollections/OrderedSet/OrderedSet.swift, Sources/_CollectionsTestSupport/AssertionContexts/Assertions.swift, Tests/OrderedCollectionsTests/OrderedSet/OrderedSetTests.swift
Resolves #158
This adds a missing operation on `OrderedSet`: filter that keeps the return type an `OrderedSet`.
The dictionary in this package already had such operation, so I followed its prior art.
One could debate if we want to preallocate the size as "same" of the current set before filtering or if not etc... Open to suggestions, it's a bit tricky to know if the result of the filter will be almost empty, or almost full after all.
- dictionary filter didn't seem to have one either
- docc
=> +OrderedSet add filter #158

Sources/OrderedCollections/Utilities/_UnsafeBitset.swift
The 5.6 stdlib introduced a new facility for temporary allocations
that promises better performance than direct allocations. Use it when
the toolchain version is above 5.6.
=> [OrderedCollection] Use standard temp allocation facility, if available

Benchmarks/Benchmarks/DequeBenchmarks.swift, Sources/DequeModule/Deque+Collection.swift, Sources/OrderedCollections/HashTable/_HashTable.swift, Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Elements.swift, Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Values.swift, Sources/OrderedCollections/OrderedDictionary/OrderedDictionary.swift, Sources/OrderedCollections/OrderedSet/OrderedSet+UnorderedView.swift, Sources/OrderedCollections/OrderedSet/OrderedSet+UnstableInternals.swift, Sources/OrderedCollections/OrderedSet/OrderedSet.swift, Utils/swift-collections.xcworkspace/xcshareddata/xcschemes/DequeModule.xcscheme
As @Lukasa discovered in #164, the `_modify` accessor in `Deque`'s index subscript tends to call malloc unless it happens to get inlined into the caller. Try to prevent this performance bottleneck by force-inlining this accessor.
To mitigate potential code size issues, move the preparation/finalization steps into separate functions that aren't force-inlined.
Resolves #164.
=> Force-inline _modify accessors to work around a performance issue

Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Initializers.swift, Sources/OrderedCollections/OrderedDictionary/OrderedDictionary.swift, Tests/OrderedCollectionsTests/OrderedDictionary/OrderedDictionary Tests.swift
Add `@_disfavoredOverload` attributes to resolve edge-case ambiguities with overloads that only differ between tuple labels. In some situations, the compiler seems to be of two minds about whether `(Key, Value)` is compatible with `(key: Key, value: Value)` or vice versa.
`@_disfavoredOverload` is not a stable attribute; using it involves some risk in case future compilers remove it or change its behavior. In the worst case, we may have to publish a new release to fix such issues.
Resolves #125.
=> [OrderedDictionary] Resolve call-site ambiguities

Sources/OrderedCollections/OrderedDictionary/OrderedDictionary.swift
Fix a code sample that was referring to the standard `Dictionary` instead of `OrderedDictionary`.
=> [OrderedDictionary] Tiny documentation fix

Sources/OrderedCollections/OrderedSet/OrderedSet+Partial SetAlgebra+Predicates.swift
`OrderedSet`'s documentation mistakenly refers to the subset relation when explaining what `isSuperset` is doing.
=> [OrderedSet] Tiny doc fixes for isSuperset.

Documentation/OrderedDictionary.md
Minor typo fix: Move `rethrows` before allow.
=> Fix `rethrows` position

Sources/BitCollections/BitSet/BitSet+Extras.swift, Sources/BitCollections/BitSet/BitSet+SetAlgebra basics.swift, Sources/_CollectionsTestSupport/AssertionContexts/Combinatorics.swift, Sources/_CollectionsTestSupport/Utilities/DictionaryAPIChecker.swift, Sources/_CollectionsTestSupport/Utilities/SetAPIChecker.swift, Tests/BitCollectionsTests/BitSetTests.swift, Tests/OrderedCollectionsTests/OrderedDictionary/OrderedDictionary Tests.swift, Tests/OrderedCollectionsTests/OrderedSet/OrderedSetTests.swift, Tests/PersistentCollectionsTests/PersistentDictionary Tests.swift
Add the `SetAPIChecker` test protocol, useful for validating the API surface of set-like types, ensuring that we haven’t forgotten to implement members that are part of users’ baseline expectations. Like its sister `DictionaryAPIChecker`, the protocol is defined in `_CollectionsTestSupport` and it is restricted for use in tests within this package. 
The new test protocol has already caught one missing API -- `BitSet` forgot to implement `remove(at:)` (oops). Add it now.
While we're here, move the non-standard APIs out of `DictionaryAPIChecker` and into a new protocol called `DictionaryAPIExtras`. This allows us to validate that the main protocol matches `Dictionary` in the stdlib.
=> [test] Check baseline API expectations for set-like types

Sources/PersistentCollections/Node/_Node+Builder.swift, Sources/PersistentCollections/Node/_Node+Initializers.swift, Sources/PersistentCollections/Node/_Node+Structural intersection.swift, Sources/PersistentCollections/Node/_Node+Structural subtracting.swift, Sources/PersistentCollections/Node/_Node+Subtree Insertions.swift, Sources/PersistentCollections/PersistentDictionary/PersistentDictionary+Collection.swift, Sources/PersistentCollections/PersistentDictionary/PersistentDictionary+Initializers.swift, Sources/PersistentCollections/PersistentDictionary/PersistentDictionary+Values.swift, Sources/PersistentCollections/PersistentDictionary/PersistentDictionary.swift, Sources/PersistentCollections/PersistentSet/PersistentSet+Collection.swift, Sources/PersistentCollections/PersistentSet/PersistentSet+Extras.swift, Sources/PersistentCollections/PersistentSet/PersistentSet+SetAlgebra Initializers.swift, Sources/PersistentCollections/PersistentSet/PersistentSet+SetAlgebra basics.swift, Sources/PersistentCollections/PersistentSet/PersistentSet+SetAlgebra formIntersection.swift, Sources/PersistentCollections/PersistentSet/PersistentSet+SetAlgebra formSymmetricDifference.swift, Sources/PersistentCollections/PersistentSet/PersistentSet+SetAlgebra formUnion.swift, Sources/PersistentCollections/PersistentSet/PersistentSet+SetAlgebra intersection.swift, Sources/PersistentCollections/PersistentSet/PersistentSet+SetAlgebra isDisjoint.swift, Sources/PersistentCollections/PersistentSet/PersistentSet+SetAlgebra isEqual.swift, Sources/PersistentCollections/PersistentSet/PersistentSet+SetAlgebra isStrictSubset.swift, Sources/PersistentCollections/PersistentSet/PersistentSet+SetAlgebra isStrictSuperset.swift, Sources/PersistentCollections/PersistentSet/PersistentSet+SetAlgebra isSubset.swift, Sources/PersistentCollections/PersistentSet/PersistentSet+SetAlgebra isSuperset.swift, Sources/PersistentCollections/PersistentSet/PersistentSet+SetAlgebra subtract.swift, Sources/PersistentCollections/PersistentSet/PersistentSet+SetAlgebra subtracting.swift, Sources/PersistentCollections/PersistentSet/PersistentSet+SetAlgebra symmetricDifference.swift, Sources/PersistentCollections/PersistentSet/PersistentSet+SetAlgebra union.swift, Sources/PersistentCollections/PersistentSet/PersistentSet.swift, Sources/_CollectionsTestSupport/Utilities/SetAPIChecker.swift, Tests/PersistentCollectionsTests/PersistentSet Tests.swift
This adds customary overloads and some missing customization points, making `PersistentSet` work more like what's expected of a set-like type.
=> Fleshing out `PersistentSet`

Sources/BitCollections/BitSet/BitSet+Extras.swift, Sources/BitCollections/BitSet/BitSet._UnsafeHandle.swift
The `BitSet.subscript(member:)` setter had an (in retrospect) obvious invariant violation when the update deleted the maximum item in the set.
(This was already covered by the existing tests, although they need to be run with internal consistency checking enabled.)
=> [BitSet] Fix invariant violation in member subscript

Sources/BitCollections/BitSet/BitSet._UnsafeHandle.swift, Sources/PersistentCollections/Node/_Node+Initializers.swift, Sources/PersistentCollections/Node/_Node+Primitive Removals.swift, Sources/PersistentCollections/Node/_Node+Primitive Replacement.swift, Sources/PersistentCollections/Node/_Node+Storage.swift, Sources/PersistentCollections/Node/_Node+Structural merge.swift, Sources/PersistentCollections/Node/_Node+Subtree Insertions.swift, Sources/PersistentCollections/Node/_Node+Subtree Modify.swift, Sources/PersistentCollections/Node/_Node+Subtree Removals.swift, Sources/PersistentCollections/PersistentDictionary/PersistentDictionary+Codable.swift, Sources/_CollectionsTestSupport/Utilities/DictionaryAPIChecker.swift, Sources/_CollectionsUtilities/UnsafeMutableBufferPointer+SE-0370.swift, Tests/PersistentCollectionsTests/PersistentCollections Fixtures.swift, Tests/PersistentCollectionsTests/PersistentDictionary Tests.swift
This is mostly about adding more type declarations to deal with type checker limitations in the older compiler. This also includes workarounds that allow better support for `CodingKeyRepresentable` in `PersistentDictionary`, and it fixes a couple of small oversights on various #else branches.
=> Restore support for building with Swift 5.5

Sources/PriorityQueueModule/Heap+Invariants.swift, Sources/PriorityQueueModule/Heap.swift, Tests/PriorityQueueTests/HeapTests.swift
Adds two methods to change either the minimum or maximum element of a `Heap` instance.  If the value changes enough that the previous second-place element now surpasses it, that former second-place element will take over for the heap's min/max element.
For testing purposes, I needed a way to precisely define a heap's pre-test state.  Therefore, I also added a new initializer that receives an exact storage layout as input.  It's a fail-able initializer.  This requires a testing function.  There is such a procedure locked in the debug-only invariant code.  I moved that code to a new unconditional method that both the new initializer and the invariant-test code both reference.
=> [Heap] Change value of minimum or maximum element

Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Elements.swift, Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Partial MutableCollection.swift, Sources/OrderedCollections/OrderedSet/OrderedSet+Partial MutableCollection.swift, Utils/swift-collections.xcworkspace/xcshareddata/swiftpm/Package.resolved
=> [OrderedCollections] Update docs to state that the sort algorithm is stable

Sources/BitCollections/BitSet/BitSet.Counted.swift, Sources/BitCollections/BitSet/BitSet.Index.swift, Sources/HeapModule/Heap+Descriptions.swift, Sources/OrderedCollections/HashTable/_HashTable+Testing.swift, Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Descriptions.swift, Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Elements.SubSequence.swift, Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Elements.swift, Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Values.swift, Sources/OrderedCollections/OrderedSet/OrderedSet+Descriptions.swift, Sources/OrderedCollections/OrderedSet/OrderedSet+SubSequence.swift, Sources/OrderedCollections/OrderedSet/OrderedSet+UnorderedView.swift, Sources/PersistentCollections/PersistentDictionary/PersistentDictionary+Collection.swift, Sources/PersistentCollections/PersistentDictionary/PersistentDictionary+Descriptions.swift, Sources/PersistentCollections/PersistentDictionary/PersistentDictionary+Keys.swift, Sources/PersistentCollections/PersistentDictionary/PersistentDictionary+Values.swift, Sources/PersistentCollections/PersistentSet/PersistentSet+Collection.swift, Tests/BitCollectionsTests/BitSetTests.swift, Tests/HeapTests/HeapTests.swift, Tests/OrderedCollectionsTests/OrderedDictionary/OrderedDictionary+Elements Tests.swift, Tests/OrderedCollectionsTests/OrderedDictionary/OrderedDictionary+Values Tests.swift, Tests/OrderedCollectionsTests/OrderedSet/OrderedSetTests.swift, Tests/PersistentCollectionsTests/PersistentDictionary Tests.swift, Tests/PersistentCollectionsTests/PersistentDictionary.Keys Tests.swift, Tests/PersistentCollectionsTests/PersistentDictionary.Values Tests.swift, Tests/PersistentCollectionsTests/PersistentSet Tests.swift, Utils/swift-collections.xcworkspace/xcshareddata/xcschemes/Collections.xcscheme
Review and update `CustomStringConvertible` and `CustomDebugStringConvertible` conformances.
Added conformances:
- `OrderedDictionary.Values`
- `OrderedDictionary.Elements.Subsequence`
- `OrderedSet.SubSequence`
- `Heap`
- `BitSet.Index`
- `PersistentDictionary.Keys`
- `PersistentDictionary.Values`
- `PersistentDictionary.Index`
- `PersistentSet.Index`
=> Review & update descriptions throughout the package

Utils/swift-collections.xcworkspace/xcshareddata/xcschemes/BitCollections.xcscheme, Utils/swift-collections.xcworkspace/xcshareddata/xcschemes/Collections.xcscheme, Utils/swift-collections.xcworkspace/xcshareddata/xcschemes/CollectionsBenchmark.xcscheme, Utils/swift-collections.xcworkspace/xcshareddata/xcschemes/CollectionsTestSupport.xcscheme, Utils/swift-collections.xcworkspace/xcshareddata/xcschemes/DequeModule.xcscheme, Utils/swift-collections.xcworkspace/xcshareddata/xcschemes/HeapModule.xcscheme, Utils/swift-collections.xcworkspace/xcshareddata/xcschemes/OrderedCollections.xcscheme, Utils/swift-collections.xcworkspace/xcshareddata/xcschemes/PersistentCollections.xcscheme, Utils/swift-collections.xcworkspace/xcshareddata/xcschemes/benchmark.xcscheme, Utils/swift-collections.xcworkspace/xcshareddata/xcschemes/memory-benchmark.xcscheme, Utils/swift-collections.xcworkspace/xcshareddata/xcschemes/swift-collections-Package.xcscheme
This explicitly disables implicit dependency tracking in the (non-public) Xcode schemes, on the off chance it does anything.
=> [Xcode] Disable implicit dependencies

Sources/BitCollections/BitSet/BitSet+CustomReflectable.swift, Sources/OrderedCollections/OrderedSet/OrderedSet+CustomReflectable.swift, Tests/BitCollectionsTests/BitSetTests.swift, Tests/OrderedCollectionsTests/OrderedSet/OrderedSetTests.swift
These are set types, so their custom mirrors should have the `.set` display style, not `.collection`.
=> [OrderedSet, BitSet] Fix custom mirror display style

Documentation/Reviews/2022-10-31.ShareableHashedCollections/ShareableHashedCollections.md
DocC likes to omit these, but I find that the remaining partial signatures are rather hard to understand on their own. (In DocC's cases, the issue is somewhat mitigated by the fact these are clickable links.)
=> [ShareableHashedCollections] API Review: add missing `mutating` keywords

Sources/OrderedCollections/HashTable/_Hashtable+Header.swift
This PR contains a minor documentation fix for a typo in `_Hashtable+Header.swift`.
=> [Hashtable] Minor Documentation Fix (Typo)

Sources/ShareableHashedCollections/Node/_Node+Initializers.swift
Add import statement missing from one of the source files in ShareableHashedCollections. (Development versions of Swift complain that this is going to become an error in the future.)
=> [ShareableHashedCollections] Add missing import

Sources/BitCollections/BitSet/BitSet+Initializers.swift, Sources/BitCollections/BitSet/BitSet+SetAlgebra isStrictSubset.swift, Sources/BitCollections/BitSet/BitSet+SetAlgebra isStrictSuperset.swift, Sources/BitCollections/BitSet/BitSet.Index.swift, Sources/OrderedCollections/OrderedSet/OrderedSet+Partial SetAlgebra intersection.swift, Sources/OrderedCollections/OrderedSet/OrderedSet+Partial SetAlgebra isStrictSubset.swift, Sources/OrderedCollections/OrderedSet/OrderedSet+Partial SetAlgebra isStrictSuperset.swift, Sources/OrderedCollections/OrderedSet/OrderedSet+Partial SetAlgebra isSubset.swift, Sources/OrderedCollections/OrderedSet/OrderedSet+Partial SetAlgebra subtracting.swift, Sources/OrderedCollections/OrderedSet/OrderedSet+Partial SetAlgebra symmetricDifference.swift, Sources/OrderedCollections/OrderedSet/OrderedSet.swift
This resolves new warnings produced by development toolchains of Swift, of the form below:
```
'<Foo>' cannot be used in an '@inlinable' function because '_CollectionsUtilities' was not 
imported by this file; this is an error in Swift 6
```
=> Fix warnings in development versions of Swift

Sources/HashTreeCollections/Node/_Node+Structural merge.swift, Sources/HashTreeCollections/TreeDictionary/TreeDictionary+Filter.swift, Sources/HashTreeCollections/TreeDictionary/TreeDictionary+Initializers.swift, Sources/HashTreeCollections/TreeDictionary/TreeDictionary+Keys.swift, Sources/HashTreeCollections/TreeDictionary/TreeDictionary+MapValues.swift, Sources/HashTreeCollections/TreeDictionary/TreeDictionary+Merge.swift, Tests/HashTreeCollectionsTests/Utilities.swift
The in-place dictionary merge operation fails to update the count of the dictionary, leaving it in an invalid state.
Fix this and also add the missing calls to `_invariantCheck` (here and elsewhere) that would've caught this much earlier. D'oh!
rdar://102824928
=> [TreeDictionary] Fix in-place merge operation to properly update the count

cmake/modules/SwiftSupport.cmake
Windows uses `ARM64` for `CMAKE_SYSTEM_PROCESSOR` which does not match the current spellings.
=> build: add ARM64 to the architecture mappings for Windows

Sources/BitCollections/BitSet/BitSet+Extras.swift
This was caught by the newly randomized testing that was enabled in 4849d54.
=> Fix off by one error in BitSet

Sources/RopeModule/BigString/Basics/BigString+Index.swift
These help implementing conversions between `String.Index` and `BigString.Index`. Direct index conversions without the corresponding collection values aren't legitimate, but unfortunately they are sometimes necessary.
rdar://107778676
=> Expose a handful of BigString.Index methods

Sources/HashTreeCollections/HashNode/_HashNode+Builder.swift, Sources/RopeModule/Rope/Basics/Rope+Builder.swift, Sources/RopeModule/Rope/Basics/Rope+Debugging.swift, Sources/RopeModule/Rope/Basics/Rope+Invariants.swift, Sources/RopeModule/Rope/Basics/Rope+_Node.swift, Sources/RopeModule/Rope/Basics/Rope+_Storage.swift, Sources/RopeModule/Rope/Basics/Rope+_UnmanagedLeaf.swift, Sources/RopeModule/Rope/Basics/Rope+_UnsafeHandle.swift, Sources/RopeModule/Rope/Basics/Rope.swift, Sources/RopeModule/Rope/Basics/RopeMetric.swift, Sources/RopeModule/Rope/Basics/_RopeItem.swift, Sources/RopeModule/Rope/Basics/_RopePath.swift, Sources/RopeModule/Rope/Basics/_RopeVersion.swift, Sources/RopeModule/Rope/Conformances/Rope+Collection.swift, Sources/RopeModule/Rope/Conformances/Rope+Index.swift, Sources/RopeModule/Rope/Conformances/Rope+Sequence.swift, Sources/RopeModule/Rope/Operations/Rope+Append.swift, Sources/RopeModule/Rope/Operations/Rope+Extract.swift, Sources/RopeModule/Rope/Operations/Rope+Find.swift, Sources/RopeModule/Rope/Operations/Rope+ForEachWhile.swift, Sources/RopeModule/Rope/Operations/Rope+Insert.swift, Sources/RopeModule/Rope/Operations/Rope+Join.swift, Sources/RopeModule/Rope/Operations/Rope+MutatingForEach.swift, Sources/RopeModule/Rope/Operations/Rope+Remove.swift, Sources/RopeModule/Rope/Operations/Rope+RemoveSubrange.swift, Sources/RopeModule/Rope/Operations/Rope+Split.swift, Sources/RopeModule/Utilities/Optional Utilities.swift, Utils/swift-collections.xcworkspace/xcshareddata/xcschemes/_RopeModule.xcscheme
This is crucial for the performance of code that directly uses `Rope`.
=> Make most of Rope inlinable

Sources/RopeModule/Utilities/String.Index+ABI.swift
This member isn’t currently used, but unlike its counterpart in the stdlib, this one accidentally sets the character-alignment bit.
=> BigString: Fix String.Index._knownScalarAligned

Sources/OrderedCollections/HashTable/_HashTable+UnsafeHandle.swift, Sources/OrderedCollections/Utilities/_UnsafeBitset.swift
Upgrading to Xcode 14.3/Swift 5.8 results in 2 deprecation warnings caused by [SE-0370](https://github.com/apple/swift-evolution/blob/main/proposals/0370-pointer-family-initialization-improvements.md):
I have:
- replaced the deprecated method with the new one wrapped inside a swift version directive
- tested it with Xcode 14.3 (Swift 5.8) and Xcode 14.2 (Swift 5.7.2)
=> Fix deprecated UnsafeMutablePointer.assign(repeating:count) method

Sources/RopeModule/Rope/Basics/Rope+_Node.swift
`Rope._Node` wasn’t declared `Sendable`, and that triggered valid warnings.
=> Rope: Fix `Sendable` conformance

Package.swift, README.md
Swift 5.8 is out now, so let’s bump the minimum required toolchain to Swift 5.6. (The package wants to support three major language releases, and now that 5.8 is out, supporting 5.5 would bump that to four.)
=> Require Swift 5.6

Sources/OrderedCollections/OrderedDictionary/OrderedDictionary.swift
It currently takes some mental gymnastics or deep data structures background to grok if OrderedDictionary's keys and values are ordered. These minor additions to the docs make that more explicit. If this sort of change is welcome I'm happy to clarify some of the other data structures as well. 
- [n/a] I've added tests covering all new code paths my change adds to the project (if appropriate).
- [n/a] I've added benchmarks covering new functionality (if appropriate).
- [n/a] I've verified that my change does not break any existing tests or introduce unexplained benchmark regressions.
=> [OrderedDictionary] Explicitly mention in documentation that keys/values are ordered

Sources/HashTreeCollections/TreeDictionary/TreeDictionary.swift, Sources/HashTreeCollections/TreeSet/TreeSet+Extras.swift, Sources/HashTreeCollections/TreeSet/TreeSet+SetAlgebra basics.swift
The HashCollections module includes several mutating methods that dereference unmanaged references to internal nodes after the last usage of `self`. Prevent the compiler from destroying `self` before we’re done working within descendants of its tree.
=> [HashCollections] Ensure `self` doesn’t get destroyed before we’re done working with it

Sources/BitCollections/BitArray/BitArray.swift, Sources/BitCollections/BitSet/BitSet+BidirectionalCollection.swift, Sources/BitCollections/BitSet/BitSet.Counted.swift, Sources/BitCollections/BitSet/BitSet.Index.swift, Sources/BitCollections/BitSet/BitSet.swift, Sources/DequeModule/Deque+Collection.swift, Sources/DequeModule/Deque+Sendable.swift, Sources/HashTreeCollections/TreeDictionary/TreeDictionary+Codable.swift, Sources/HashTreeCollections/TreeDictionary/TreeDictionary+Collection.swift, Sources/HashTreeCollections/TreeDictionary/TreeDictionary+Keys.swift, Sources/HashTreeCollections/TreeDictionary/TreeDictionary+Sendable.swift, Sources/HashTreeCollections/TreeDictionary/TreeDictionary+Sequence.swift, Sources/HashTreeCollections/TreeDictionary/TreeDictionary+Values.swift, Sources/HashTreeCollections/TreeSet/TreeSet+Collection.swift, Sources/HashTreeCollections/TreeSet/TreeSet+Sendable.swift, Sources/HashTreeCollections/TreeSet/TreeSet+Sequence.swift, Sources/HeapModule/Heap.swift, Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Elements.SubSequence.swift, Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Elements.swift, Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Sendable.swift, Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Sequence.swift, Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Values.swift, Sources/OrderedCollections/OrderedSet/OrderedSet+SubSequence.swift, Sources/OrderedCollections/OrderedSet/OrderedSet+UnorderedView.swift, Sources/OrderedCollections/OrderedSet/OrderedSet+UnstableInternals.swift, Tests/HashTreeCollectionsTests/TreeDictionary Tests.swift
Now that this package requires Swift 5.6, these are no longer necessary.
=> Remove obsolete swift(>=5.5)/swift(>=5.6) checks

cmake/modules/SwiftSupport.cmake
The Windows architecture spelling is ARM64 which we would not match and thus would be unable to build for ARM64.
Replace this paragraph with a description of your changes and rationale. Provide links to an existing issue or external references/discussions, if appropriate.
=> build: support ARM64 spelling

Sources/_CollectionsUtilities/IntegerTricks/Integer rank.swift.gyb, Sources/_CollectionsUtilities/IntegerTricks/autogenerated/Integer rank.swift
It turns out `UInt.bitWidth` is getting too eagerly inlined, so conditions based on it trigger spurious “code will never be executed” warnings. Silence those by switching to looking at `MemoryLayout<UInt>`, which doesn’t get turned into a constant *that* early.
=> [CollectionUtilities] Silence a warning on 32 bit platforms

Sources/BitCollections/BitSet/BitSet._UnsafeHandle.swift, Tests/BitCollectionsTests/BitSetTests.swift
If the interval we're checking against happens to end on a storage word boundary, then we mistakenly returned false even if the comparison should've succeeded.
This was caught by exercising the 32-bit code paths on watchOS -- one of the tests happened to use 130..<160 as the range, and 160 == 5 * 32. Add new test cases that would've caught this on 64 bit systems, too.
=> [BitSet] Fix a thinko in BitSet.isEqualSet

Sources/RopeModule/Rope/Operations/Rope+Split.swift, Tests/RopeModuleTests/TestBigString.swift, Tests/RopeModuleTests/TestRope.swift
This should work:
```
var rope = Rope<Chunk>()
rope.removeSubrange(0 ..< 0)
rope.replaceSubrange(0 ..< 0, in: Chunk.Metric(), with: foobar)
```
However, both calls currently trap when trying to access (and split) a nonexistent root node.
This PR fixes that, and adds some test coverage in this area.
(It also migrates assertions in rope tests to use the CollectionsTestSupport infrastructure.)
rdar://110149070
=> Rope: Fix trap when replaceSubrange is called on an empty rope

Sources/RopeModule/Rope/Operations/Rope+Find.swift, Tests/RopeModuleTests/TestRope.swift
When looking for the rope position precisely at the end of the rope, `Rope.find(at:in:preferEnd:)` fails to return the right result: it correctly returns the `endIndex`, but it indicates that the position we’re looking for is at a large offset into that (nonexistent) element, instead of correctly reporting the remainder as zero:
```swift
let chunks = (0 ..< 5).map { Chunk(length: 10, value: $0) }
let rope = Rope<Chunk>(chunks)
// `rope` contains 5 chunks, with 50 components according to the metric `Chunk.Metric`.
let (index, remaining) = rope.find(at: 50, in: Chunk.Metric(), preferEnd: false)
print(index == rope.endIndex) // true, OK
print(remaining) // prints 50, should be 0
```
Predictably, this can have dire consequences in client code.
rdar://110191289
=> `Rope.find` returns a bogus remainder for the end position

Sources/_CollectionsTestSupport/MinimalTypes/MinimalDecoder.swift
This resolves a valid 5.9 compiler warning within the test target.
=> [1.0][test] Fix typename shadowing warning in Swift 5.9

Benchmarks/CppBenchmarks/src/CustomHash.h
C++17 has removed `std::unary_function`. Migrate to using `std::function`.
(This may break our ability to build benchmarks with older clang/libc++ releases. That is fine.)
=> [1.0][benchmark] Update std::function syntax for current C++

Sources/RopeModule/Rope/Basics/Rope+_Node.swift, Sources/RopeModule/Rope/Basics/Rope+_UnsafeHandle.swift
These render the emitted .swiftinterface unusable when the module is built with library evolution enabled.
=> [RopeModule] Remove unnecessary typealiases

Sources/HeapModule/Heap.swift
Resolves #324.
rdar://118368503
=> [Heap] Improve type-level doc comment

Documentation/OrderedSet.md, Sources/OrderedCollections/OrderedSet/OrderedSet.swift
> This PR contains a small fix for a typo in OrderedSet Documentation
I found this typo while testing the [OrdedSet Documentation - Set Operations](https://github.com/apple/swift-collections/blob/main/Documentation/OrderedSet.md#set-operations)
=> Fix typos: OrderedSet Documentation

Sources/HeapModule/Heap.swift
Resolves #325.
The new code is already covered by the `test_insert_contentsOf_exhaustive` test, which exercises everything.
=> [Heap] insert(contentsOf:) Switch to Floyd’s if we’re inserting too many items

CMakeLists.txt
With this tweak, we should be able to build the package in debug mode even on Windows.  We always use the release mode DLL form of the C/C++ runtime on Windows and can build the Swift code in Debug or Release mode optimizations.
=> build: support building in Debug mode on Windows

CMakeLists.txt
Correct the path to allow using swift-collections embedded in a larger project.  This is meant to assist with building LSP with vendored dependencies.
=> build: tweak search path for embedding

Benchmarks/Benchmarks/OrderedDictionaryBenchmarks.swift, Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Values.swift, Sources/_CollectionsTestSupport/AssertionContexts/Assertions.swift, Tests/OrderedCollectionsTests/OrderedDictionary/OrderedDictionary+Values Tests.swift
https://github.com/apple/swift-collections/issues/334
The current implementation of `OrderedDictionary.Values.==` forwards to `Sequence.elementsEqual`, which needs to perform a linear-time (`O[N]`) comparison over both collections.[1]
Since the "backing store" of our `OrderedDictionary.Values` is a `ContiguousArray`, we can forward that equality check through to `ContiguousArray`. If both `Values` instances point to the same identity, the `ContiguousArray` implementation will return early from the comparison.[2]
We perform a similar check (against the `ContiguousArray`) in our implementation of `OrderedDictionary.==`.[3]
[1] https://github.com/apple/swift/blob/main/stdlib/public/core/SequenceAlgorithms.swift#L319-L336
[2] https://github.com/apple/swift/blob/main/stdlib/public/core/Contiguo …
=> [OrderedDictionary] forward ordered dictionary values equality to values property

Benchmarks/Benchmarks/OrderedSetBenchmarks.swift, Sources/OrderedCollections/OrderedSet/OrderedSet+Equatable.swift, Sources/OrderedCollections/OrderedSet/OrderedSet+SubSequence.swift, Tests/OrderedCollectionsTests/OrderedSet/OrderedSetTests.swift
https://github.com/apple/swift-collections/pull/335
Similar to `OrderedDictionary`, we can forward our `OrderedSet` equality checks down to the `ContiguousArray` instance to take advantage of early return when both arrays point to the same identity (no need to perform a linear comparison over all elements).
A side-effect of this optimization is we also optimize `OrderedDictionary.==`, which performs an equality check on the `keys` property (which is an `OrderedSet`).[1]
[1] https://github.com/apple/swift-collections/blob/main/Sources/OrderedCollections/OrderedDictionary/OrderedDictionary%2BEquatable.swift#L20-L22
---
From:
```
public static func ==(left: Self, right: Self) -> Bool {
left.elementsEqual(right)
}
```
To:
```
public static func ==(left: Self, right: Self) -> Bool { …
```
=> [OrderedSet] forward ordered set equality to elements property

Benchmarks/Benchmarks/DequeBenchmarks.swift, Sources/DequeModule/Deque+Equatable.swift, Sources/DequeModule/Deque._Storage.swift, Tests/DequeTests/DequeTests.swift
https://github.com/apple/swift-collections/pull/335
Similar to what we added for `OrderedDictionary`, we can try and optimize our `Deque` equality checks for the case where two `Deque` instances point to the same identity.
Unlike `OrderedDictionary`, our `Deque` is not implemented on `ContiguousArray`. We can try and mimic the approach from `ContiguousArray` here in `Deque` by checking against the identity of the underlying `ManagedBufferPointer` instance.
---
From:
```
public static func ==(left: Self, right: Self) -> Bool {
left.elementsEqual(right)
}
```
To:
```
let lhsCount = left.count
if lhsCount != right.count {
return false
}
// Test referential equality.
if lhsCount == 0 || left._storage.isIdentical(to: right._storage) {
return true
}
return left.elementsEqual(right)
```
---
We …
=> [Deque] check deque equality with buffer identity

Sources/DequeModule/Deque+Collection.swift, Sources/DequeModule/Deque+Sendable.swift, Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Elements+SubSequence.swift, Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Elements.swift, Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Sendable.swift, Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Sequence.swift, Sources/OrderedCollections/OrderedDictionary/OrderedDictionary+Values.swift, Sources/OrderedCollections/OrderedSet/OrderedSet+Sendable.swift, Sources/OrderedCollections/OrderedSet/OrderedSet+SubSequence.swift, Sources/OrderedCollections/OrderedSet/OrderedSet+UnorderedView.swift, Sources/OrderedCollections/OrderedSet/OrderedSet+UnstableInternals.swift
This backports #191 to the release/1.0 branch, retrofitting that release series with proper support for Swift 5.5.
Resolves #317
=> [1.0] Backport Sendable conformances on all public types

Sources/OrderedCollections/OrderedSet/OrderedSet+Sendable.swift
`OrderedSet` has lost the condition `swift(>=5.5)` around its `Sendable` conformance, and that predictably causes issues on Swifts that predate that.
=> OrderedSet: Fix sendable conformance on old swifts

Sources/DequeModule/CMakeLists.txt, Sources/OrderedCollections/CMakeLists.txt
#343 missed updating the CMake build config. (Sadly this project has no working CI.)
Weirdly, the missing `Sendable` conformances are only causing problems on Swift 5.5 -- they must be inferred elsewhere.
=> Update CMake configuration

Sources/SortedCollections/BTree/_BTree+Partial RangeReplaceableCollection.swift, Tests/SortedCollectionsTests/BTree/BTree+Deletion Tests.swift
`_BTree.removeFirst(_:)` and `_BTree.removeLast(_:)` contains following incorrect assert:
```swift
assert(0 <= k && k < self.count, "Can't remove more items from a collection than it contains")
```
This assertion will cause a crash (in debug mode) when we call one of these functions with the same number of items as the collection contains.
This PR solves this issue by replacing `k < self.count` with `k <= self.count` in the assert.
- ~~I've added benchmarks covering new functionality (if appropriate).~~
=> Bugfix Incorrect Assert in BTree.removeFirst/removeLast

Documentation/Heap.md, Sources/HeapModule/Heap.swift, Tests/HeapTests/HeapTests.swift
This implements [@tevelee](https://forums.swift.org/u/tevelee/summary)'s suggestion from Heap's API RFC thread on the project forum:
https://forums.swift.org/t/swift-collections-1-1-heap-api-rfc/68447/5
rdar://118432031
=> [Heap] Convert min() and max() to properties

Benchmarks/Sources/Benchmarks/DequeBenchmarks.swift, Benchmarks/Sources/Benchmarks/DictionaryBenchmarks.swift, Benchmarks/Sources/Benchmarks/OrderedDictionaryBenchmarks.swift, Benchmarks/Sources/Benchmarks/OrderedSetBenchmarks.swift, Benchmarks/Sources/Benchmarks/SetBenchmarks.swift, Benchmarks/Sources/Benchmarks/ShareableSetBenchmarks.swift
We have `benchmarks` defined to measure the performance of `OrderedSet` and `OrderedDictionary` equality to confirm that equality of shared instances perform efficiently (in `O(1)` time). We would like to add `benchmarks` for `TreeSet` and `TreeDictionary` to confirm the same behavior. We can also go ahead and add those same `benchmarks` for the system `Set` and `Dictionary` implementations.
We only make changes to `benchmarks`. This diff contains no implementation changes.
In addition to the new `benchmarks`, we can also make small changes to previous `benchmarks` to make them more consistent (we migrate `same instance` to `shared` and `different instance` to `unique`.
```
swift run -c release benchmark run results.json --cycles 5 --tasks \
"Set<Int> equality, unique" \
"OrderedSet<Int> …
```
=> [Benchmarks] Add Collection Equality Benchmarks

Sources/DequeModule/_UnsafeWrappedBuffer.swift, Sources/HashTreeCollections/HashNode/_UnsafePath.swift, Sources/HashTreeCollections/TreeSet/TreeSet+ExpressibleByArrayLiteral.swift, Sources/OrderedCollections/HashTable/_HashTable+BucketIterator.swift, Sources/OrderedCollections/OrderedSet/OrderedSet.swift, Sources/RopeModule/BigString/Chunk/BigString+Chunk+Description.swift, Sources/RopeModule/Rope/Basics/RopeMetric.swift, Tests/RopeModuleTests/TestBigString.swift
This is cherry picking parts of #356 to the release/1.1 branch, shortcutting some of the prerelease prep work.
(`SortedSet` and `SortedDictionary` aren't on this branch, so this PR omits those parts.)
Thanks @rex4539!
=> [1.1] Fix typos

Sources/OrderedCollections/CMakeLists.txt
Currently OrderedCollections cmake incorrectly list "Utilities/_UnsafeBitSet.swift" instead of "Utilities/_UnsafeBitset.swift", causing build failures
=> Fix the incorrect file name in OrderedCollections cmake file

Sources/DequeModule/Deque._Storage.swift
A non-unique reference to a storage instance can legitimately become unique at any point, due to other references (say, held, by another thread) getting destroyed.
`Deque`’s `ensureUnique` implementation currently invokes the uniqueness check two times in quick succession, expecting it to return false both times. In rare circumstances, this can lead to a spurious trap in concurrent environments.
Fix this by avoiding calling `isUnique` more than once.
(We do not have a great way to exercise such concurrency issues, so this fix comes with no test case.)
Resolves #380
=> [Deque]: Fix bogus assert in Deque._Storage._ensureUnique

Tests/HashTreeCollectionsTests/TreeDictionary.Keys Tests.swift
The `test_isEqual_exhaustive` test includes a stray print statement that is flooding test output with a myriad lines of useless data.
=> [test] TreeDictionary.Keys: Remove stray print that’s flooding test output

Sources/RopeModule/Rope/Operations/Rope+Join.swift, Tests/RopeModuleTests/TestBigString.swift, Tests/RopeModuleTests/TestRope.swift
`Rope.join` has a logic error where it fails to properly ensure uniqueness of child node references before zipping the two b-trees together.
rdar://128450202
=> [Rope] Fix copy-on-write violation in Rope.join

Sources/Collections/CMakeLists.txt
This updates the cmake build (specifically the single-module, foundation toolchain build section) to install the `_FoundationCollections.a` library for the static swift build (but not install it for the non-static build). This ensures the library is present in the static swift SDK in the toolchain (as needed) but not in the standard directory. The usage of this module is still guarded by the `-allowable-client` flag written into the swift module.
=> Install the Foundation toolchain module during the static swift build

Package.swift, Sources/Future/CMakeLists.txt, Sources/Future/ContiguousStorage.swift, Sources/Future/Dummy.swift, Sources/Future/RawSpan.swift, Sources/Future/Span.swift, Tests/FutureTests/ContiguousStorageTests.swift, Tests/FutureTests/RawSpanTests.swift, Tests/FutureTests/SpanTests.swift
This adds prototypes of `Span` and `RawSpan`, types proposed and discussed in "[Safe Access to Contiguous Storage](https://forums.swift.org/t/69888)"
These additions require a recent Swift development toolchain [snapshot](https://www.swift.org/download/#snapshots), June 8th 2024 or newer.
=> Add prototypes of `Span` and `RawSpan`

Sources/Future/RawSpan.swift, Sources/Future/Span.swift, Tests/FutureTests/RawSpanTests.swift
- Remove lifetime-dependency annotations when they are the inferred default.
- Various corrections in doc-comments
- Better name for bounds-checking functions, and adding non-failing counterparts.
=> Updates: clean up keywords, improve bounds checking

Sources/Future/RawSpan.swift, Sources/Future/Span.swift, Tests/FutureTests/RawSpanTests.swift, Tests/FutureTests/SpanTests.swift
The function names are probably bad.
```swift
extension RawSpan {
func contains(other span: borrowing Self) -> Bool
func offsets(of span: borrowing Self) -> Range<Int> // traps if self.contains(span) is false
}
```
=> Span: add utilities to test span containment relationships

Sources/Future/RawSpan.swift, Tests/FutureTests/RawSpanTests.swift
Rename the `load`, `loadUnaligned`, and `view(as:)` functions, and improve their documentation.
=> Better document the unsafe operations of RawSpan

Package.swift, Sources/Future/Box.swift, Sources/Future/CMakeLists.txt, Sources/Future/Cell.swift, Sources/Future/Inout.swift, Sources/Future/RawSpan.swift, Tests/FutureTests/BoxTests.swift, Tests/FutureTests/CellTests.swift
This adds a `Box` type who is a noncopyable type that provides a safe abstraction for owning a heap allocated value as well as a `Cell` type who is a noncopyable type that provides an inline value with interior mutability and addressability.
Note: None of this builds right now as we're lacking a recent toolchain and most likely missing `dependsOn(immortal)`
=> [Future] Add Box and Cell

Sources/Future/RawSpan.swift, Sources/Future/Span.swift, Tests/FutureTests/RawSpanTests.swift
Mostly improvements to doc-comments.
The `uncheckedBounds` argument label for overloads of `extracting()` is changed to simply `unchecked`.
(`uncheckedBounds` is the label for a `Range` initializer, but it doesn't work as well here.)
=> doc-comment improvements, argument label fix

Benchmarks/Sources/Benchmarks/BigStringBenchmarks.swift, Benchmarks/Sources/benchmark-tool/main.swift, Sources/RopeModule/BigString/Basics/BigString+Ingester.swift
When ingesting a `String` instance, `BigString` assumes that the input string has a reasonably efficient UTF-8 view.
Unfortunately, that is very much not the case when the input happens to be backed by a bridged NSString object — it appears that in this case, the ingester loop invokes some operation(s) with linear complexity in the size of the entire input, rendering the ingester’s overall complexity quadratic.
The BigString ingester is only expected to operate within a single chunk at the time. It’s unclear precisely which operation triggers the quadratic behavior; ideally we should figure it out and resolve it with a more targeted fix.
In the meantime, a blunt stopgap fix is to force-transcode the input string to UTF-8 at the time the ingester is initialized. This unnecessarily wastes …
=> [BigString] Fix accidentally quadratic `BigString.init`

Sources/Future/RawSpan.swift, Sources/Future/Span.swift, Tests/FutureTests/RawSpanTests.swift, Tests/FutureTests/SpanTests.swift
Add initializers that take mutable buffer parameters, for convenience.
Update the tests to make sure they're called.
Also mark the `_indices` and `_byteOffsets` properties as `@_alwaysEmitIntoClient` to further emphasize their non-ABI status.
=> Round out Span initializers

Sources/DequeModule/_DequeBuffer.swift
Hello, How about adding the final keyword to classes that do not inherit?
Thanks for reading.
=> add 'final' keyword to class

Sources/SortedCollections/BTree/_BTree+UnsafeCursor.swift, Sources/SortedCollections/BTree/_BTree.swift, Sources/SortedCollections/BTree/_Node.UnsafeHandle+Deletion.swift
Change some unfortunate wording around invariant violations.
=> [BTree][NFC] Rephrase some comments

Sources/OrderedCollections/HashTable/_HashTable+UnsafeHandle.swift, Sources/OrderedCollections/HashTable/_HashTable.swift, Sources/OrderedCollections/OrderedSet/OrderedSet.swift
I have noticed that OrderedSet performance is slower than Dictionary if the `Element` isn't known at compile time and therefore the compiler can't specialize the implementations.
This PR replaces some of the generic functions that are generic with manual partial specialized variations that are only generic over the `Element` type.
=> Optimize unspecialized `OrderedSet.init` and `OrderedSet.firstIndex(of:)`

Sources/Future/Box.swift, Sources/Future/Containers/Container.swift, Sources/Future/Containers/RigidArray.swift, Sources/Future/Containers/Shared.swift, Sources/Future/Inout.swift, Sources/Future/LifetimeOverride.swift, Sources/Future/MutableSpan.swift, Sources/Future/OutputSpan.swift, Sources/Future/RawSpan.swift, Sources/Future/Span+Iterator.swift, Sources/Future/Span.swift, Sources/Future/StdlibSpanExtensions.swift, Tests/FutureTests/ContiguousStorageTests.swift, Tests/FutureTests/OutputSpanTests.swift, Tests/FutureTests/RawSpanTests.swift, Tests/FutureTests/SpanTests.swift, Tests/FutureTests/StdlibOutputSpanExtensionTests.swift, Tests/FutureTests/StdlibSpanExtensionTests.swift
Brings `Span` and `RawSpan` up to date with the standard library version, while preserving some functions that have been remove there.
The lifetime declaration syntax is updated to use the `@lifetime()` attributes rather than the `dependsOn()` annotations on return types.
Will now require a more recent snapshot, e.g. swift-DEVELOPMENT-SNAPSHOT-2024-11-16-a
=> Span updates

CMakeLists.txt, Sources/CMakeLists.txt, cmake/modules/SwiftSupport.cmake
Previously, libs were installed under `lib/swift/${os}`. They should be installed in the default library directory for the relevant target system.
In addition, swiftmodules were installed in the older layout format. This changes to use the standard modern layout format for swiftmodules.
- [*] I've read the [Contribution Guidelines](/README.md#contributing-to-swift-collections)
- [*] My contributions are licensed under the [Swift license](/LICENSE.txt).
- [*] I've followed the coding style of the rest of the project.
- [*] I've added tests covering all new code paths my change adds to the project (if appropriate).
- [*] I've added benchmarks covering new functionality (if appropriate).
- [*] I've verified that my change does not break any existing tests or introduce unexplained benchmark …
=> [cmake] Install libraries in standard directories

Sources/OrderedCollections/OrderedDictionary/OrderedDictionary.swift
This is a cherry pick of @Gyuni's https://github.com/apple/swift-collections/pull/445.
=> [1.2][OrderedDictionary] fix a typo

Sources/DequeModule/Deque.swift, Sources/Future/Arrays/NewArray.swift, Sources/Future/Arrays/RigidArray.swift, Sources/Future/Containers/RepeatingContainer.swift, Sources/Future/Span/UnsafeBufferPointer+Additions.swift, Tests/CollectionsTestSupportTests/StaccatoContainerTests.swift, Tests/FutureTests/RepeatingContainerTests.swift, Tests/FutureTests/RigidArrayTests.swift, Tests/FutureTests/SpanTests/RawSpanTests.swift, Tests/_CollectionsTestSupport/ConformanceCheckers/CheckContainer.swift, Tests/_CollectionsTestSupport/MinimalTypes/StaccatoContainer.swift
- Add `StaccatoContainer` for testing operations that take input containers
- Update `Container` conformance validator
- Add `RigidArray` initializers that copy data from arbitrary collections, spans and containers.
- Add `RigidArray.replaceSubrange` overloads that take spans and containers.
- Rename `RigidArray.resize(to:)` to `RigidArray.setCapacity(_:)`.
- Make `RigidArray.copy()` and `RigidArray.copy(capacity:)` public API.
=> Flesh out RigidArray even more; add complete test coverage

Package.swift, Sources/DequeModule/Deque+Container.swift, Sources/DequeModule/DynamicDeque.swift, Sources/DequeModule/RigidDeque.swift, Sources/Future/Arrays/DynamicArray.swift, Sources/Future/Arrays/NewArray.swift, Sources/Future/Arrays/RigidArray.swift, Sources/Future/Containers/BidirectionalContainer.swift, Sources/Future/Containers/Container.swift, Sources/Future/Containers/ContainerAlgorithms.swift, Sources/Future/Containers/ContiguousContainer.swift, Sources/Future/Containers/MutableContainer.swift, Sources/Future/Containers/RandomAccessContainer.swift, Sources/Future/Containers/RepeatingContainer.swift, Sources/Future/Span/LifetimeOverride.swift, Sources/Future/Span/OutputSpan.swift, Sources/Future/Span/SpanExtensions.swift, Sources/Future/Span/UnsafeBufferPointer+Additions.swift, Sources/Future/Tools/Box.swift, Sources/Future/Tools/Inout.swift, Sources/Future/Tools/Shared.swift, Tests/CollectionsTestSupportTests/MinimalTypeConformances.swift, Tests/CollectionsTestSupportTests/StaccatoContainerTests.swift, Tests/FutureTests/ArrayTests/DynamicArrayTests.swift, Tests/FutureTests/ArrayTests/RigidArrayTests.swift, Tests/FutureTests/ContiguousStorageTests.swift, Tests/_CollectionsTestSupport/AssertionContexts/Assertions+Containers.swift, Tests/_CollectionsTestSupport/ConformanceCheckers/CheckContainer.swift, Tests/_CollectionsTestSupport/MinimalTypes/StaccatoContainer.swift
Rip out all traces of SwiftCompatibilitySpan availability; it isn't actually functional in 6.2.
Older compiler builds seem to struggle with slightly more complex mutating dependencies and Container protocol requirements that have defaults on RandomAccessContainer.
The tests are still passing, which is a good sign.
=> Add support for older builds of the 6.2 compiler

CMakeLists.txt, Sources/CMakeLists.txt, cmake/modules/PlatformInfo.cmake, cmake/modules/SwiftSupport.cmake
This cleans up how the CMake build of Swift-Collections installs swiftmodules to use the swift module triple expected by the compiler for a given target triple instead of trying to recreate the correct architecture name in CMake. The existing computation is incorrect for modules building for x86_64 FreeBSD machines, causing swift-foundation to fail to build. Letting the compiler specify what it expects the module triple to be for a given target triple will be more robust.
resolves: https://github.com/swiftlang/swift-foundation/issues/1230
=> Install swiftmodules with full module triple

Sources/OrderedCollections/OrderedSet/OrderedSet+Partial SetAlgebra union.swift, Tests/OrderedCollectionsTests/OrderedSet/OrderedSetTests.swift
This PR adds a new public function on `appending(contentsOf:)` to `OrderedSet`. It is functionally equivalent to `union(_:)`  but is more explicit about ordering. I find myself looking for this, rather than `union` because a mutating `append(contentsOf:)` already exists. 
A counter argument to this addition would be to minimize duplicative APIs as much as possible to reduce API surface area. However, there's already precedent for "alternative" functions, given `append(contentsOf:)` and `formUnion(_:)` coexist. And in this case I believe it adds sufficient value to justify the addition.
It's second nature to look for an "append" on ordered collections in Swift. Arrays are ubiquitous and an `append(contentsOf:)` exists. However, unlike Array, OrderedSet does not support the `+` operator, so …
=> [OrderedSet] Add `OrderedSet.appending(contentsOf:)`

Sources/HashTreeCollections/HashNode/_HashNode+Storage.swift, Sources/HashTreeCollections/HashNode/_HashTreeStatistics.swift
ManagedBuffer.capacity depends on malloc introspection (e.g., `malloc_size`), which is not available on this platform -- and is thus marked as such.
Here, _HashNode.Storage is a ManagedBuffer. Thankfully, the uses of .capacity are fairly limited: one for statistic purposes, which we just completely omit on the platform, and the other, setting a minimum capacity in the header by the buffer's .capacity; the alternative being setting that minimum capacity directly.
=> ManagedBuffer.capacity is unavailable on OpenBSD.

Sources/HeapModule/Heap+UnsafeHandle.swift, Sources/HeapModule/Heap.swift, Tests/HeapTests/HeapTests.swift
Heap._UnsafeHandle has minValue and maxValue. Original functionality was `minValue`, `if a == b, return b`. For `maxValue`, `if a == b, return a`. In both cases, this is the opposite tiebreaker choice from `Swift.min` and `Swift.max`.
`Heap.replaceMax` used `Heap._UnsafeHandle.maxValue` while `Heap.max` used `Swift.max`, and due to different tiebreaker choices, led to inconsistency as seen in #439 .
Therefore I go ahead and update `Heap._UnsafeHandle.maxValue/minValue` to be consistent with `Swift.max/min`.
Fixes #439
=> Align Heap._UnsafeHandle min/maxValue tie-breaking with Swift.min/max

Sources/HeapModule/Heap.swift, Tests/HeapTests/HeapTests.swift
This PR introduces a new method `Heap.removeAll(where:)` that allows users to remove all elements satisfying a given predicate from the heap in O(n) time. This is done by filtering the buffer and re-heapifying.
Closes #255
=> Add Heap.removeAll(where:)

Tests/RopeModuleTests/TestBigString.swift
On recent enough stdlibs, we can now just print the index directly to get the same effect.
=> [Rope] Resolve deprecation warnings on `String.Index._description`

Sources/OrderedCollections/OrderedSet/OrderedSet+Partial SetAlgebra union.swift
I thought the example code for `OrderedSet.appending(contentsOf:)` should be `a.appending(contentsOf: b)` instead of `a.union(b)`. Please close this PR if this is intended.
=> fix comment for OrderedSet.appending(contentsOf:)

Benchmarks/Package.resolved, Benchmarks/Package.swift, Utils/swift-collections.xcworkspace/xcshareddata/swiftpm/Package.resolved
Let's adopt the new swift-collections-benchmark tag.
- swift-collections-benchmark 0.0.4
- Swift 6.1 minimum toolchain version
- macOS 15 minimum deployment target
=> Bump requirements of nested benchmarking package

CMakeLists.txt, cmake/modules/PlatformInfo.cmake
Fixing two issues in the CMake build:
- There was a typo in the CMake `PlatformInfo.cmake` misspelling `CMAKE_Swift_COMPILER_TARGET`
- It looks like there was a merge conflict where the resolution ended up including the PlatformInfo module twice. Deleting one of them.
=> Fix CMake build

Sources/OrderedCollections/OrderedSet/OrderedSet.swift
Code presented as an example usage of `OrderedSet` doesn't compile since mutating `sort` function is called on immutable `let`.
=> Fix OrderedSet example usage

cmake/modules/PlatformInfo.cmake
This PR cherry picks https://github.com/apple/swift-collections/pull/482/commits, which fixes a typo in the CMake build that is blocking https://github.com/swiftlang/swift/pull/83310.
=> Fix CMake build for `release/1.2`

Sources/SortedCollections/BTree/_Node.UnsafeHandle+Deletion.swift, Tests/SortedCollectionsTests/SortedSet/SortedSet Tests.swift
This PR fixes an issue where calling `remove(at:)` on a `SortedSet` would correctly remove the element but fail to update the set’s `count`, leading to inconsistency between the actual contents and the reported size of the set.
The root cause was a missing update to the internal B-Tree node’s `subtreeCount` when removing an element from a node's child node. This PR ensures the internal node properly decrements its `subtreeCount` after removal, keeping the tree metadata consistent.
Resolves #441
=> [SortedSet] Fix subtreeCount inconsistency after remove at index

Sources/BitCollections/BitArray/BitArray+BitwiseOperations.swift, Sources/BitCollections/BitArray/BitArray+Codable.swift, Sources/BitCollections/BitArray/BitArray+Initializers.swift, Sources/BitCollections/BitArray/BitArray+RandomBits.swift, Sources/BitCollections/BitArray/BitArray+Testing.swift, Sources/BitCollections/BitSet/BitSet+BidirectionalCollection.swift, Sources/BitCollections/BitSet/BitSet+Random.swift, Sources/BitCollections/BitSet/BitSet+SetAlgebra basics.swift
Some classes lack of  macros (`COLLECTIONS_SINGLE_MODULE`) judgment when `import InternalCollectionsUtilities`, then add it like everywhere else.
=> Add the missing COLLECTIONS_SINGLE_MODULE when import InternalCollectionsUtils

Xcode/Collections.xcodeproj/project.pbxproj
This adds the new trailing elements sources to the Xcode Collections target
=> [Xcode] Add trailing elements to xcodeproj

README.md, Sources/Collections/Collections.docc/Collections.md
Docc doesn't really like reexported modules, so the `Collections` default target couldn't access any of the other symbols from its documentation. Provide relative links to those instead and add some blurbs about the new `RigidArray` and `UniqueArray`.
=> [Docs] Fix landing page of collections documentation

.github/ISSUE_TEMPLATE/BUG_REPORT.md, .github/PULL_REQUEST_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE/NEW.md
The PR template's links to the Swift license and contribution guidelines have been broken for ages -- fix them.
=> Fix links in GitHub templates
